/*
 * MacSurf - macos9_brotli.h
 *
 * Public surface of the vendored single-file Brotli decoder (macos9_brotli.c,
 * generated by tools/flatten_brotli.sh from google/brotli, MIT). The full
 * decoder internals live in the .c; this header exposes only what the WOFF2
 * reconstructor (macos9_woff2.c) needs.
 */

#ifndef MACSURF_MACOS9_BROTLI_H
#define MACSURF_MACOS9_BROTLI_H

#include <stddef.h>
#include <stdint.h>

/* Result of a one-shot BrotliDecoderDecompress() call. The enum and the
 * prototype below are byte-identical to the ones inside macos9_brotli.c
 * (from include/brotli/decode.h) so the declarations never diverge. */
typedef enum {
  BROTLI_DECODER_RESULT_ERROR = 0,
  BROTLI_DECODER_RESULT_SUCCESS = 1,
  BROTLI_DECODER_RESULT_NEEDS_MORE_INPUT = 2,
  BROTLI_DECODER_RESULT_NEEDS_MORE_OUTPUT = 3
} BrotliDecoderResult;

/* One-shot memory-to-memory decompression (the WOFF2 path knows the exact
 * uncompressed size up front, so no streaming/growable machinery is needed).
 *
 *   encoded_size / encoded_buffer : the brotli stream
 *   *decoded_size                 : in  = capacity of decoded_buffer
 *                                   out = bytes written on SUCCESS
 *   decoded_buffer                : caller-owned output
 *
 * Returns BROTLI_DECODER_RESULT_SUCCESS (1) on success; ERROR (0) if the
 * stream is corrupt, the buffer is too small, or allocation failed.
 */
BrotliDecoderResult BrotliDecoderDecompress(
        size_t encoded_size, const uint8_t encoded_buffer[],
        size_t *decoded_size, uint8_t decoded_buffer[]);

#endif /* MACSURF_MACOS9_BROTLI_H */
