/*
 * fixes148 -- gap and row-gap parsers for MacSurf.
 *
 * libcss upstream does not implement CSS3 gap/row-gap. MacTrove alone
 * uses `gap:` 76 times, so dropping these at tokenization leaves flex
 * items touching with zero spacing.
 *
 * fixes148 shipped a scope compromise where BOTH row-gap and the `gap:`
 * shorthand emitted CSS_PROP_COLUMN_GAP, so the two axes shared storage
 * and `gap: ROW COL` silently discarded the row value.
 *
 * Real row-gap landed as its own property (CSS_PROP_ROW_GAP with scalar
 * computed-style storage -- the bits[16] array is full), so:
 *   - row-gap:      emits CSS_PROP_ROW_GAP
 *   - gap: A        emits BOTH CSS_PROP_ROW_GAP and CSS_PROP_COLUMN_GAP
 *                   with A (per CSS Box Alignment a single value applies
 *                   to both axes)
 *   - gap: A B      emits CSS_PROP_ROW_GAP (A) then CSS_PROP_COLUMN_GAP (B)
 */

#include <assert.h>
#include <string.h>

#include "bytecode/bytecode.h"
#include "bytecode/opcodes.h"
#include "parse/properties/properties.h"
#include "parse/properties/utils.h"

/**
 * Shared helper: parse a single <length> | normal | inherit | initial |
 * revert | unset | calc() value and emit it as a declaration for the
 * given gap property.
 *
 * Matches the shape of css__parse_column_gap in autogenerated_column_gap.c
 * but is hand-written so the target property is explicit.
 */
static css_error parse_gap_value(css_language *c,
		const parserutils_vector *vector, int32_t *ctx,
		css_style *result, opcode_t prop)
{
	int32_t orig_ctx = *ctx;
	css_error error;
	const css_token *token;
	bool match;

	token = parserutils_vector_iterate(vector, ctx);
	if (token == NULL) {
		*ctx = orig_ctx;
		return CSS_INVALID;
	}

	if ((token->type == CSS_TOKEN_IDENT) &&
			(lwc_string_caseless_isequal(
			token->idata, c->strings[INHERIT],
			&match) == lwc_error_ok && match)) {
		error = css_stylesheet_style_inherit(result, prop);

	} else if ((token->type == CSS_TOKEN_IDENT) &&
			(lwc_string_caseless_isequal(
			token->idata, c->strings[INITIAL],
			&match) == lwc_error_ok && match)) {
		error = css_stylesheet_style_initial(result, prop);

	} else if ((token->type == CSS_TOKEN_IDENT) &&
			(lwc_string_caseless_isequal(
			token->idata, c->strings[REVERT],
			&match) == lwc_error_ok && match)) {
		error = css_stylesheet_style_revert(result, prop);

	} else if ((token->type == CSS_TOKEN_IDENT) &&
			(lwc_string_caseless_isequal(
			token->idata, c->strings[UNSET],
			&match) == lwc_error_ok && match)) {
		error = css_stylesheet_style_unset(result, prop);

	} else if ((token->type == CSS_TOKEN_IDENT) &&
			(lwc_string_caseless_isequal(
			token->idata, c->strings[NORMAL],
			&match) == lwc_error_ok && match)) {
		error = css__stylesheet_style_appendOPV(result,
				prop, 0, COLUMN_GAP_NORMAL);

	} else if ((token->type == CSS_TOKEN_FUNCTION) &&
			(lwc_string_caseless_isequal(
			token->idata, c->strings[CALC],
			&match) == lwc_error_ok && match)) {
		error = css__parse_calc(c, vector, ctx, result,
				buildOPV(prop, 0, COLUMN_GAP_CALC),
				UNIT_PX);

	} else {
		css_fixed length = 0;
		uint32_t unit = 0;
		*ctx = orig_ctx;

		error = css__parse_unit_specifier(c, vector, ctx,
				UNIT_PX, &length, &unit);
		if (error != CSS_OK) {
			*ctx = orig_ctx;
			return error;
		}

		if (length < 0) {
			*ctx = orig_ctx;
			return CSS_INVALID;
		}

		if ((unit & UNIT_MASK_COLUMN_GAP) == 0) {
			*ctx = orig_ctx;
			return CSS_INVALID;
		}

		error = css__stylesheet_style_appendOPV(result,
				prop, 0, COLUMN_GAP_SET);
		if (error != CSS_OK) {
			*ctx = orig_ctx;
			return error;
		}

		error = css__stylesheet_style_vappend(result, 2, length, unit);
	}

	if (error != CSS_OK)
		*ctx = orig_ctx;

	return error;
}

/**
 * row-gap: parse identical to column-gap, emit as CSS_PROP_ROW_GAP.
 */
css_error css__parse_row_gap(css_language *c,
		const parserutils_vector *vector, int32_t *ctx,
		css_style *result)
{
	return parse_gap_value(c, vector, ctx, result, CSS_PROP_ROW_GAP);
}

/**
 * gap: row-gap <column-gap>? -- shorthand.
 *
 * Per CSS Box Alignment: `gap` is shorthand for row-gap + column-gap.
 * If only one value is given, it applies to both axes.
 */
css_error css__parse_gap(css_language *c,
		const parserutils_vector *vector, int32_t *ctx,
		css_style *result)
{
	int32_t orig_ctx = *ctx;
	int32_t second_start;
	css_error error;
	const css_token *token;

	/* Parse the first (row) value. */
	error = parse_gap_value(c, vector, ctx, result, CSS_PROP_ROW_GAP);
	if (error != CSS_OK) {
		*ctx = orig_ctx;
		return error;
	}

	/* Swallow optional whitespace, peek for second value. */
	consumeWhitespace(vector, ctx);
	second_start = *ctx;
	token = parserutils_vector_peek(vector, *ctx);
	if (token == NULL || tokenIsChar(token, ';') ||
			tokenIsChar(token, '}') ||
			tokenIsChar(token, '!')) {
		/* Only one value -- per spec it applies to both axes, so
		 * re-emit the same tokens as the column-gap. */
		int32_t reparse_ctx = orig_ctx;

		error = parse_gap_value(c, vector, &reparse_ctx,
				result, CSS_PROP_COLUMN_GAP);
		if (error != CSS_OK) {
			/* Cannot happen for tokens already accepted once;
			 * keep the row-gap and stay well-formed. */
			return CSS_OK;
		}

		return CSS_OK;
	}

	/* A second value is the column-gap per spec. A malformed second
	 * value shouldn't invalidate the whole declaration: keep the
	 * row-gap emitted above and ignore the rest. */
	error = parse_gap_value(c, vector, ctx, result,
			CSS_PROP_COLUMN_GAP);
	if (error != CSS_OK) {
		*ctx = second_start;
		return CSS_OK;
	}

	return CSS_OK;
}
