/*
 * This file is part of LibCSS.
 * Licensed under the MIT License,
 *                http://www.opensource.org/licenses/mit-license.php
 * Copyright 2026 MacSurf
 *
 * Parse `-macsurf-object-position`.
 *
 * V2 grammar (fixes201): supports both keyword and numeric forms.
 *
 * Keyword form (V1 path, unchanged):
 *   left | center | right | top | bottom
 * with the standard CSS defaults:
 *   left      -> left center
 *   top      -> center top
 *   center   -> center center
 *
 * Numeric form (fixes201 addition): percentage or px-length on
 * either axis, mixable. Examples:
 *   object-position: 25% 75%
 *   object-position: 10px 20px
 *   object-position: 50% 10px
 *
 * Keyword and numeric forms emit DIFFERENT bytecode:
 *
 *   Keyword: appendOPV with the 4-bit packed (x|y) value in the
 *   OPV value field. Cascade writes the 4-bit slot in word 15 via
 *   set_macsurf_object_position(). Default sentinel is "use
 *   keyword fallback" (bit 31 of the numeric int32 is 0).
 *
 *   Numeric: appendOPV with value=0x0080 (SET marker, same
 *   pattern as aspect_ratio / background_size), followed by a
 *   vappend of the packed int32. Cascade reads the int32 from the
 *   bytecode stream and writes it to the new
 *   `macsurf_object_position_xy` field at end of `_i` struct.
 *
 *   Packed int32 layout (mirrors comment in
 *   autogenerated_computed.h next to the field declaration):
 *     bit  31      has-value flag (1 = use numeric, 0 = keyword)
 *     bit  30      h-unit (0 = percent, 1 = px)
 *     bits 29..16  h-value Q8.6 signed (14 bits, range -128..127.98)
 *     bit  15      reserved (0)
 *     bit  14      v-unit (0 = percent, 1 = px)
 *     bits 13..0   v-value Q8.6 signed (14 bits)
 *
 * Resolution: percent values resolve at consumer time against
 * (slot_dim - object_dim) per CSS spec; px values are absolute
 * offsets within the slot. The consumer
 * (html_redraw_apply_object_fit) reads the numeric int32 first
 * via css_computed_macsurf_object_position_xy(); if bit 31 is 0,
 * it falls back to the keyword via
 * css_computed_macsurf_object_position().
 *
 * Lengths in non-px units (em, rem, vw, etc.) parse as if px for
 * V2 -- accurate cross-unit resolution would need the unit_len_ctx
 * which isn't available at parse time.
 */

#include <assert.h>
#include <string.h>

#include "bytecode/bytecode.h"
#include "bytecode/opcodes.h"
#include "parse/properties/properties.h"
#include "parse/properties/utils.h"

static uint8_t
macsurf_object_position_pack(uint8_t x, uint8_t y)
{
	return (uint8_t)(((x & 0x3) << 2) | (y & 0x3));
}

enum macsurf_object_position_token_kind {
	MACSURF_OBJECT_POS_TOK_INVALID = 0,
	MACSURF_OBJECT_POS_TOK_HORIZ,
	MACSURF_OBJECT_POS_TOK_VERT,
	MACSURF_OBJECT_POS_TOK_CENTER
};

/* fixes201 - packed-int32 encoder. Clamps to Q8.6 14-bit signed
 * range so the value field can't overflow the bitslot. Caller
 * passes h_value / v_value as IEEE float in real units (percent or
 * px). */
static int32_t macsurf_object_position_pack_xy(
		float h_value, int h_is_px,
		float v_value, int v_is_px)
{
	int h_q86;
	int v_q86;
	uint32_t packed;

	h_q86 = (int)(h_value * 64.0f);
	v_q86 = (int)(v_value * 64.0f);
	if (h_q86 >  8191) h_q86 =  8191;
	if (h_q86 < -8192) h_q86 = -8192;
	if (v_q86 >  8191) v_q86 =  8191;
	if (v_q86 < -8192) v_q86 = -8192;

	packed = (uint32_t)1u << 31;
	packed |= (uint32_t)(h_is_px ? 1u : 0u) << 30;
	packed |= ((uint32_t)h_q86 & 0x3FFFu) << 16;
	packed |= (uint32_t)(v_is_px ? 1u : 0u) << 14;
	packed |= ((uint32_t)v_q86 & 0x3FFFu);
	return (int32_t)packed;
}

/* fixes201 - try to read one position component (percentage,
 * length, or NUMBER token where 0 is acceptable). Returns 1 on
 * success and fills *out_value (real units) + *out_is_px (1 if
 * length, 0 if percentage). Returns 0 on non-numeric (so the
 * caller can fall through to keyword parsing). */
static int macsurf_object_position_read_numeric(
		const css_token *token,
		float *out_value, int *out_is_px)
{
	size_t conv = 0;
	css_fixed length = 0;

	if (token == NULL || token->idata == NULL) return 0;

	if (token->type == CSS_TOKEN_PERCENTAGE) {
		length = css__number_from_lwc_string(token->idata, false,
				&conv);
		if (conv == 0) return 0;
		*out_value = (float)length / 1024.0f;
		*out_is_px = 0;
		return 1;
	}
	if (token->type == CSS_TOKEN_DIMENSION) {
		const char *u;
		size_t ulen;
		int is_px = 1;
		length = css__number_from_lwc_string(token->idata, false,
				&conv);
		if (conv == 0) return 0;
		u = lwc_string_data(token->idata) + conv;
		ulen = lwc_string_length(token->idata) - conv;
		/* Treat non-px units (em / rem / vw / ...) as px for V2 -
		 * accurate cross-unit resolution would need the unit_len_ctx
		 * which isn't available at parse time. */
		(void)u;
		(void)ulen;
		(void)is_px;
		*out_value = (float)length / 1024.0f;
		*out_is_px = 1;
		return 1;
	}
	if (token->type == CSS_TOKEN_NUMBER) {
		/* Unitless number is only valid as 0; otherwise reject. */
		length = css__number_from_lwc_string(token->idata, false,
				&conv);
		if (conv == 0) return 0;
		if (length != 0) return 0;
		*out_value = 0.0f;
		*out_is_px = 1;
		return 1;
	}
	return 0;
}

css_error css__parse_macsurf_object_position(css_language *c,
		const parserutils_vector *vector, int32_t *ctx,
		css_style *result)
{
	int32_t orig_ctx = *ctx;
	css_error error;
	const css_token *token;
	bool match;
	uint8_t x = CSS_MACSURF_OBJECT_POSITION_CENTER;
	uint8_t y = CSS_MACSURF_OBJECT_POSITION_CENTER;
	uint8_t value1 = 0, value2 = 0;
	enum macsurf_object_position_token_kind kind1 =
		MACSURF_OBJECT_POS_TOK_INVALID;
	enum macsurf_object_position_token_kind kind2 =
		MACSURF_OBJECT_POS_TOK_INVALID;
	int consumed = 0;

	token = parserutils_vector_iterate(vector, ctx);
	if ((token == NULL) || (token->type != CSS_TOKEN_IDENT)) {
		*ctx = orig_ctx;
		return CSS_INVALID;
	}

	if ((lwc_string_caseless_isequal(
			token->idata, c->strings[INHERIT],
			&match) == lwc_error_ok && match)) {
		return css_stylesheet_style_inherit(result,
				CSS_PROP_MACSURF_OBJECT_POSITION);
	}
	if ((lwc_string_caseless_isequal(
			token->idata, c->strings[INITIAL],
			&match) == lwc_error_ok && match)) {
		return css_stylesheet_style_initial(result,
				CSS_PROP_MACSURF_OBJECT_POSITION);
	}
	if ((lwc_string_caseless_isequal(
			token->idata, c->strings[REVERT],
			&match) == lwc_error_ok && match)) {
		return css_stylesheet_style_revert(result,
				CSS_PROP_MACSURF_OBJECT_POSITION);
	}
	if ((lwc_string_caseless_isequal(
			token->idata, c->strings[UNSET],
			&match) == lwc_error_ok && match)) {
		return css_stylesheet_style_unset(result,
				CSS_PROP_MACSURF_OBJECT_POSITION);
	}

	*ctx = orig_ctx;

	/* fixes201: numeric (percent / length) path.
	 *
	 * Peek the first token; if it's a percentage / dimension /
	 * number, take the numeric path. Read up to two numeric
	 * values (first = horizontal, second = vertical; missing
	 * second axis defaults to 50% center).
	 *
	 * On success this returns directly with a bytecode-stream
	 * value; the keyword loop below never runs. On failure (e.g.
	 * malformed numeric) the function returns CSS_INVALID without
	 * consuming the keyword loop. */
	{
		const css_token *peek = parserutils_vector_peek(vector, *ctx);
		if (peek != NULL && (
				peek->type == CSS_TOKEN_PERCENTAGE ||
				peek->type == CSS_TOKEN_DIMENSION ||
				peek->type == CSS_TOKEN_NUMBER)) {
			float h_val = 50.0f;
			int h_is_px = 0;
			float v_val = 50.0f;
			int v_is_px = 0;
			int32_t packed_xy;

			if (!macsurf_object_position_read_numeric(peek,
					&h_val, &h_is_px)) {
				*ctx = orig_ctx;
				return CSS_INVALID;
			}
			parserutils_vector_iterate(vector, ctx);
			consumeWhitespace(vector, ctx);

			peek = parserutils_vector_peek(vector, *ctx);
			if (peek != NULL && (
					peek->type == CSS_TOKEN_PERCENTAGE ||
					peek->type == CSS_TOKEN_DIMENSION ||
					peek->type == CSS_TOKEN_NUMBER)) {
				if (!macsurf_object_position_read_numeric(
						peek, &v_val, &v_is_px)) {
					*ctx = orig_ctx;
					return CSS_INVALID;
				}
				parserutils_vector_iterate(vector, ctx);
			}
			/* Single-value form: per CSS spec, missing second
			 * axis defaults to 50% (centre on Y). h_val stays as
			 * parsed. */

			packed_xy = macsurf_object_position_pack_xy(
					h_val, h_is_px, v_val, v_is_px);

			/* Emit the "numeric SET" OPV + the packed value via
			 * the bytecode stream (aspect_ratio / background_size
			 * pattern). The cascade in s_macsurf_object_position.c
			 * detects the 0x0080 SET value and reads the int32. */
			error = css__stylesheet_style_appendOPV(result,
					CSS_PROP_MACSURF_OBJECT_POSITION,
					0, 0x0080 /* numeric SET */);
			if (error != CSS_OK) {
				*ctx = orig_ctx;
				return error;
			}
			error = css__stylesheet_style_vappend(result, 1,
					(css_fixed)packed_xy);
			if (error != CSS_OK) {
				*ctx = orig_ctx;
				return error;
			}
			return CSS_OK;
		}
	}

	while (consumed < 2) {
		token = parserutils_vector_peek(vector, *ctx);
		if ((token == NULL) || (token->type != CSS_TOKEN_IDENT)) {
			break;
		}

		if ((lwc_string_caseless_isequal(token->idata,
				c->strings[LIBCSS_LEFT],
				&match) == lwc_error_ok && match)) {
			if (consumed == 0) {
				kind1 = MACSURF_OBJECT_POS_TOK_HORIZ;
				value1 = CSS_MACSURF_OBJECT_POSITION_START;
			} else {
				kind2 = MACSURF_OBJECT_POS_TOK_HORIZ;
				value2 = CSS_MACSURF_OBJECT_POSITION_START;
			}
		} else if ((lwc_string_caseless_isequal(token->idata,
				c->strings[LIBCSS_RIGHT],
				&match) == lwc_error_ok && match)) {
			if (consumed == 0) {
				kind1 = MACSURF_OBJECT_POS_TOK_HORIZ;
				value1 = CSS_MACSURF_OBJECT_POSITION_END;
			} else {
				kind2 = MACSURF_OBJECT_POS_TOK_HORIZ;
				value2 = CSS_MACSURF_OBJECT_POSITION_END;
			}
		} else if ((lwc_string_caseless_isequal(token->idata,
				c->strings[TOP],
				&match) == lwc_error_ok && match)) {
			if (consumed == 0) {
				kind1 = MACSURF_OBJECT_POS_TOK_VERT;
				value1 = CSS_MACSURF_OBJECT_POSITION_START;
			} else {
				kind2 = MACSURF_OBJECT_POS_TOK_VERT;
				value2 = CSS_MACSURF_OBJECT_POSITION_START;
			}
		} else if ((lwc_string_caseless_isequal(token->idata,
				c->strings[BOTTOM],
				&match) == lwc_error_ok && match)) {
			if (consumed == 0) {
				kind1 = MACSURF_OBJECT_POS_TOK_VERT;
				value1 = CSS_MACSURF_OBJECT_POSITION_END;
			} else {
				kind2 = MACSURF_OBJECT_POS_TOK_VERT;
				value2 = CSS_MACSURF_OBJECT_POSITION_END;
			}
		} else if ((lwc_string_caseless_isequal(token->idata,
				c->strings[CENTER],
				&match) == lwc_error_ok && match)) {
			if (consumed == 0) {
				kind1 = MACSURF_OBJECT_POS_TOK_CENTER;
				value1 = CSS_MACSURF_OBJECT_POSITION_CENTER;
			} else {
				kind2 = MACSURF_OBJECT_POS_TOK_CENTER;
				value2 = CSS_MACSURF_OBJECT_POSITION_CENTER;
			}
		} else {
			break;
		}

		parserutils_vector_iterate(vector, ctx);
		consumed++;
	}

	if (consumed == 0) {
		*ctx = orig_ctx;
		return CSS_INVALID;
	}

	if (consumed == 1) {
		if (kind1 == MACSURF_OBJECT_POS_TOK_HORIZ) {
			x = value1;
		} else if (kind1 == MACSURF_OBJECT_POS_TOK_VERT) {
			y = value1;
		} else if (kind1 != MACSURF_OBJECT_POS_TOK_CENTER) {
			*ctx = orig_ctx;
			return CSS_INVALID;
		}
	} else {
		if (kind1 == MACSURF_OBJECT_POS_TOK_CENTER &&
				kind2 == MACSURF_OBJECT_POS_TOK_CENTER) {
			/* defaults already correct */
		} else if (kind1 == MACSURF_OBJECT_POS_TOK_HORIZ &&
				kind2 == MACSURF_OBJECT_POS_TOK_VERT) {
			x = value1;
			y = value2;
		} else if (kind1 == MACSURF_OBJECT_POS_TOK_VERT &&
				kind2 == MACSURF_OBJECT_POS_TOK_HORIZ) {
			x = value2;
			y = value1;
		} else if (kind1 == MACSURF_OBJECT_POS_TOK_CENTER &&
				kind2 == MACSURF_OBJECT_POS_TOK_HORIZ) {
			x = value2;
		} else if (kind1 == MACSURF_OBJECT_POS_TOK_CENTER &&
				kind2 == MACSURF_OBJECT_POS_TOK_VERT) {
			y = value2;
		} else if (kind1 == MACSURF_OBJECT_POS_TOK_HORIZ &&
				kind2 == MACSURF_OBJECT_POS_TOK_CENTER) {
			x = value1;
		} else if (kind1 == MACSURF_OBJECT_POS_TOK_VERT &&
				kind2 == MACSURF_OBJECT_POS_TOK_CENTER) {
			y = value1;
		} else {
			*ctx = orig_ctx;
			return CSS_INVALID;
		}
	}

	error = css__stylesheet_style_appendOPV(result,
			CSS_PROP_MACSURF_OBJECT_POSITION,
			0, macsurf_object_position_pack(x, y));
	if (error != CSS_OK) {
		*ctx = orig_ctx;
	}

	return error;
}
