/*
 * This file is part of LibCSS.
 * Licensed under the MIT License,
 *                http://www.opensource.org/licenses/mit-license.php
 * Copyright 2026 MacSurf (fixes116)
 *
 * Parse `object-fit`: fill | contain | cover | none | scale-down.
 *
 * Mapped onto CSS_PROP_OBJECT_FIT (0x086). Single-keyword grammar.
 * Cloned from the box_sizing autogenerated parser; the only difference
 * is the keyword set.
 */

#include <assert.h>
#include <string.h>

#include "bytecode/bytecode.h"
#include "bytecode/opcodes.h"
#include "parse/properties/properties.h"
#include "parse/properties/utils.h"

css_error css__parse_object_fit(css_language *c,
		const parserutils_vector *vector, int32_t *ctx,
		css_style *result)
{
	int32_t orig_ctx = *ctx;
	css_error error;
	const css_token *token;
	bool match;

	token = parserutils_vector_iterate(vector, ctx);
	if ((token == NULL) || ((token->type != CSS_TOKEN_IDENT))) {
		*ctx = orig_ctx;
		return CSS_INVALID;
	}

	if ((lwc_string_caseless_isequal(
			token->idata, c->strings[INHERIT],
			&match) == lwc_error_ok && match)) {
		error = css_stylesheet_style_inherit(result,
				CSS_PROP_OBJECT_FIT);

	} else if ((lwc_string_caseless_isequal(
			token->idata, c->strings[INITIAL],
			&match) == lwc_error_ok && match)) {
		error = css_stylesheet_style_initial(result,
				CSS_PROP_OBJECT_FIT);

	} else if ((lwc_string_caseless_isequal(
			token->idata, c->strings[REVERT],
			&match) == lwc_error_ok && match)) {
		error = css_stylesheet_style_revert(result,
				CSS_PROP_OBJECT_FIT);

	} else if ((lwc_string_caseless_isequal(
			token->idata, c->strings[UNSET],
			&match) == lwc_error_ok && match)) {
		error = css_stylesheet_style_unset(result,
				CSS_PROP_OBJECT_FIT);

	} else if ((lwc_string_caseless_isequal(
			token->idata, c->strings[FILL],
			&match) == lwc_error_ok && match)) {
		error = css__stylesheet_style_appendOPV(result,
				CSS_PROP_OBJECT_FIT,
				0, CSS_OBJECT_FIT_FILL);

	} else if ((lwc_string_caseless_isequal(
			token->idata, c->strings[CONTAIN],
			&match) == lwc_error_ok && match)) {
		error = css__stylesheet_style_appendOPV(result,
				CSS_PROP_OBJECT_FIT,
				0, CSS_OBJECT_FIT_CONTAIN);

	} else if ((lwc_string_caseless_isequal(
			token->idata, c->strings[COVER],
			&match) == lwc_error_ok && match)) {
		error = css__stylesheet_style_appendOPV(result,
				CSS_PROP_OBJECT_FIT,
				0, CSS_OBJECT_FIT_COVER);

	} else if ((lwc_string_caseless_isequal(
			token->idata, c->strings[NONE],
			&match) == lwc_error_ok && match)) {
		error = css__stylesheet_style_appendOPV(result,
				CSS_PROP_OBJECT_FIT,
				0, CSS_OBJECT_FIT_NONE);

	} else if ((lwc_string_caseless_isequal(
			token->idata, c->strings[SCALE_DOWN],
			&match) == lwc_error_ok && match)) {
		error = css__stylesheet_style_appendOPV(result,
				CSS_PROP_OBJECT_FIT,
				0, CSS_OBJECT_FIT_SCALE_DOWN);

	} else {
		error = CSS_INVALID;
	}

	if (error != CSS_OK)
		*ctx = orig_ctx;

	return error;
}
