/*
 * MacSurf stub — testament.h
 * Normally generated by the NetSurf build system with git info.
 * Stub provides empty defines so dt_version.c compiles.
 */
#ifndef NETSURF_TESTAMENT_H
#define NETSURF_TESTAMENT_H

#define CI_BUILD "macsurf"

#endif
