#!/usr/bin/env python3
"""
CW8 / C89 compatibility audit for vendored BearSSL.

Scans every .c / .h file under macSSL/bearssl/ and counts occurrences of
constructs that CodeWarrior 8 (C89 mode) does not accept, plus PPC code-gen
hazards that MacSurf has been bitten by before (CW8 long long miscompile,
union casts in autogenerated tables, etc.).

Categories scanned:
  cpp_comment        - `//` line comments (single line, EXCLUDING URLs in
                       block comments like http:// or https://)
  inline_kw          - `inline` storage-class keyword (not as substring of
                       identifiers)
  for_scope_int      - `for (TYPE NAME = ...)` integer for-scope decl
  for_scope_ptr      - `for (TYPE *NAME = ...)` pointer for-scope decl
  designated_init    - `.field = value` designated initializer
  compound_literal   - `(struct foo){ ... }` compound literal
  variadic_macro     - `#define FOO(...)` or `__VA_ARGS__`
  long_long          - `long long` keyword (PPC 64-bit miscompile hazard)
  uint64_intrinsic   - `(u)int64_t` usage (PPC 64-bit miscompile hazard)
  restrict_kw        - `restrict` keyword
  attribute_gnu      - `__attribute__` GCC extension
  builtin_gnu        - `__builtin_*` GCC intrinsic
  snprintf           - snprintf / vsnprintf (MSL on CW8 is unreliable)
  size_t_printf      - `%zu` / `%zd` (C99 length specifier)
  posix_header       - POSIX-only header includes (errno.h, strings.h, etc.)
  flexible_array     - `type name[];` flexible array member (struct tail)
  hex_float          - `0x1.8p-1` style C99 hex float literal
  union_cast         - `(union_typedef)expr` GNU cast-to-union
  static_inline_hdr  - `static inline` inside a .h file
  forward_enum       - `enum foo;` forward declaration without definition

Output: one row per file with non-zero counts, plus aggregate totals and a
top-offenders summary at the end.

Usage:
  python3 tools/audit_cw8_compat.py [--json out.json] [--root bearssl]
"""

import argparse
import json
import os
import re
import sys
from collections import defaultdict


# ---------------------------------------------------------------------------
# Comment / string stripping
# ---------------------------------------------------------------------------
#
# CW8 audit requires us to scan source-level constructs only -- not text that
# happens to appear inside /* ... */ blocks or string literals. The most
# common false-positive class in CLAUDE.md is `//` inside a block comment
# containing a URL (e.g. `* See http://www.opensource.org/...`).
#
# We do a single forward pass over the text, tracking the lexical state
# (NORMAL, BLOCK_COMMENT, LINE_COMMENT, STRING, CHAR). When stripping for
# pattern-matching purposes we replace removed regions with spaces (so line
# numbers and column offsets stay correct).

def strip_comments_and_strings(text):
    """Return a copy of `text` with /*...*/ , // , "..." , '...' replaced
    by spaces (preserving newlines and length). Used to avoid scanning
    inside comments and string literals."""
    out = []
    i = 0
    n = len(text)
    state = "N"  # N=normal, B=block, L=line, S=string, C=char
    while i < n:
        c = text[i]
        nxt = text[i + 1] if i + 1 < n else ""
        if state == "N":
            if c == "/" and nxt == "*":
                state = "B"
                out.append("  ")
                i += 2
                continue
            if c == "/" and nxt == "/":
                state = "L"
                out.append("  ")
                i += 2
                continue
            if c == '"':
                state = "S"
                out.append(" ")
                i += 1
                continue
            if c == "'":
                state = "C"
                out.append(" ")
                i += 1
                continue
            out.append(c)
            i += 1
        elif state == "B":
            if c == "*" and nxt == "/":
                state = "N"
                out.append("  ")
                i += 2
                continue
            out.append("\n" if c == "\n" else " ")
            i += 1
        elif state == "L":
            if c == "\n":
                state = "N"
                out.append("\n")
                i += 1
                continue
            out.append(" ")
            i += 1
        elif state == "S":
            if c == "\\" and nxt:
                out.append("  ")
                i += 2
                continue
            if c == '"':
                state = "N"
                out.append(" ")
                i += 1
                continue
            out.append("\n" if c == "\n" else " ")
            i += 1
        elif state == "C":
            if c == "\\" and nxt:
                out.append("  ")
                i += 2
                continue
            if c == "'":
                state = "N"
                out.append(" ")
                i += 1
                continue
            out.append("\n" if c == "\n" else " ")
            i += 1
    return "".join(out)


# ---------------------------------------------------------------------------
# Patterns
# ---------------------------------------------------------------------------

# `//` line comments -- scan the *raw* text but exclude lines whose entire
# `//`-prefix is contained inside an active block comment. We do this by
# looking at the stripped text: if stripped text at that offset is whitespace
# (because it was inside a block comment), skip.
def count_cpp_line_comments(raw, stripped):
    n = 0
    locs = []
    for m in re.finditer(r"//", raw):
        # Was this `//` inside a block comment, string, or char literal?
        # If stripped[m.start():m.start()+2] is "  " (two spaces), it was
        # stripped, meaning it was already inside a comment/string. Skip.
        if stripped[m.start():m.start() + 2] == "  ":
            continue
        n += 1
        line = raw.count("\n", 0, m.start()) + 1
        locs.append(line)
    return n, locs[:8]


# inline keyword (whole word, not substring of an identifier).
RE_INLINE = re.compile(r"\binline\b")
RE_RESTRICT = re.compile(r"\brestrict\b")
RE_ATTRIBUTE = re.compile(r"\b__attribute__\b")
RE_BUILTIN = re.compile(r"\b__builtin_\w+\b")
RE_LONG_LONG = re.compile(r"\blong\s+long\b")
RE_UINT64 = re.compile(r"\b(u?int(?:_least|_fast)?64_t|uint64|int64)\b")
RE_SNPRINTF = re.compile(r"\bv?snprintf\b")
RE_SIZE_T_PRINTF = re.compile(r'%[-+#0 ]*\*?[0-9]*\.?\*?[0-9]*[zZ][diouxX]')
RE_HEX_FLOAT = re.compile(r"\b0[xX][0-9a-fA-F]+\.[0-9a-fA-F]*[pP][-+]?\d+")
RE_VA_ARGS = re.compile(r"\b__VA_ARGS__\b|#\s*define\s+\w+\s*\([^)]*\.\.\.\)")

# Designated initializer: `.name =` where the dot is NOT preceded by an
# identifier character (so we don't match `foo.x = 1` which is a struct
# assignment). The pattern needs to look at the *previous non-whitespace*
# character. We approximate with a regex that allows `,`, `{`, `;`, or
# start-of-line before the optional whitespace and `.`.
RE_DESIGNATED = re.compile(
    r"(^|[\s,{;])\.[A-Za-z_][A-Za-z_0-9]*\s*=", re.MULTILINE
)

# For-scope declarations
RE_FOR_INT_SCOPE = re.compile(
    r"\bfor\s*\(\s*"
    r"(?:unsigned\s+|signed\s+|const\s+|volatile\s+|static\s+)*"
    r"(?:char|short|int|long|float|double|size_t|ssize_t|"
    r"u?int(?:8|16|32|64)_t|u?int(?:_least|_fast)?(?:8|16|32|64)_t)"
    r"(?:\s+(?:unsigned|signed|long|short))*"
    r"\s+[A-Za-z_][A-Za-z_0-9]*\s*="
)
RE_FOR_PTR_SCOPE = re.compile(
    r"\bfor\s*\(\s*"
    r"(?:const\s+|volatile\s+|static\s+)*"
    r"(?:struct\s+\w+|union\s+\w+|enum\s+\w+|[A-Za-z_][A-Za-z_0-9]*)"
    r"\s*\*+\s*[A-Za-z_][A-Za-z_0-9]*\s*="
)

# Compound literal: `(typename){`. Requires the opening paren to be preceded
# by something that can introduce an expression (not e.g. a function
# definition). Approximate: any `)` immediately followed by `{` after a
# `(type)` cast-looking sequence on the same line. This is a heuristic.
RE_COMPOUND_LIT = re.compile(
    r"\(\s*(?:const\s+|volatile\s+|struct\s+|union\s+|enum\s+)*"
    r"[A-Za-z_][A-Za-z_0-9]*(?:\s*\*+)*\s*\)\s*\{"
)

# Flexible array member: `type name[];` as last member of a struct.
# Heuristic -- look for `[];` at end of a line.
RE_FLEX_ARRAY = re.compile(r"\[\s*\]\s*;")

# Forward enum: `enum foo;` not followed by `{` (i.e. just a declaration).
RE_FORWARD_ENUM = re.compile(r"\benum\s+[A-Za-z_][A-Za-z_0-9]*\s*;")

# POSIX-only headers we care about.
POSIX_HEADERS = {
    "errno.h",
    "strings.h",
    "sys/types.h",
    "sys/time.h",
    "sys/stat.h",
    "unistd.h",
    "fcntl.h",
    "dirent.h",
    "iconv.h",
    "netinet/in.h",
    "arpa/inet.h",
    "netdb.h",
    "pthread.h",
}
RE_INCLUDE = re.compile(r'#\s*include\s*[<"]([^>"]+)[>"]')

# Union cast: `(typedef_name)expr` where typedef resolves to a union. We
# can't resolve typedefs statically, so we approximate by flagging *any*
# C-style cast whose typedef name ends in `_or_calc`, `_value`, `_union`,
# etc. -- but that misses unknown cases. A simpler heuristic is to look
# for the exact pattern `(<id>)0` since the autogen tables use literal 0
# casts. Conservative: report the count and let humans verify.
RE_C_CAST_TO_ID_ZERO = re.compile(
    r"\(\s*[A-Za-z_][A-Za-z_0-9]*\s*\)\s*0\b"
)

# static inline in header -- a CW8 problem because the function gets
# emitted in every TU.
RE_STATIC_INLINE = re.compile(r"\bstatic\s+inline\b")


# ---------------------------------------------------------------------------
# Per-file scan
# ---------------------------------------------------------------------------

def scan_file(path):
    """Return a dict of category -> int counts for one file."""
    with open(path, "rb") as f:
        raw_bytes = f.read()
    try:
        raw = raw_bytes.decode("utf-8")
    except UnicodeDecodeError:
        raw = raw_bytes.decode("latin-1")
    stripped = strip_comments_and_strings(raw)

    out = defaultdict(int)
    samples = defaultdict(list)

    # Comments are scanned against raw text but filtered by stripped state.
    n_cpp, cpp_lines = count_cpp_line_comments(raw, stripped)
    out["cpp_comment"] = n_cpp
    samples["cpp_comment"] = cpp_lines

    # All other patterns scan the stripped text.
    def count_and_sample(label, regex):
        matches = list(regex.finditer(stripped))
        out[label] = len(matches)
        sample_lines = []
        for m in matches[:5]:
            line = stripped.count("\n", 0, m.start()) + 1
            sample_lines.append(line)
        samples[label] = sample_lines

    count_and_sample("inline_kw", RE_INLINE)
    count_and_sample("restrict_kw", RE_RESTRICT)
    count_and_sample("attribute_gnu", RE_ATTRIBUTE)
    count_and_sample("builtin_gnu", RE_BUILTIN)
    count_and_sample("long_long", RE_LONG_LONG)
    count_and_sample("uint64_intrinsic", RE_UINT64)
    count_and_sample("snprintf", RE_SNPRINTF)
    count_and_sample("size_t_printf", RE_SIZE_T_PRINTF)
    count_and_sample("hex_float", RE_HEX_FLOAT)
    count_and_sample("variadic_macro", RE_VA_ARGS)
    count_and_sample("designated_init", RE_DESIGNATED)
    count_and_sample("for_scope_int", RE_FOR_INT_SCOPE)
    count_and_sample("for_scope_ptr", RE_FOR_PTR_SCOPE)
    count_and_sample("compound_literal", RE_COMPOUND_LIT)
    count_and_sample("flexible_array", RE_FLEX_ARRAY)
    count_and_sample("forward_enum", RE_FORWARD_ENUM)
    count_and_sample("union_cast_zero", RE_C_CAST_TO_ID_ZERO)

    if path.endswith(".h"):
        count_and_sample("static_inline_hdr", RE_STATIC_INLINE)

    # POSIX headers
    posix_hits = []
    for m in RE_INCLUDE.finditer(stripped):
        h = m.group(1).strip()
        if h in POSIX_HEADERS:
            posix_hits.append(h)
    out["posix_header"] = len(posix_hits)
    samples["posix_header"] = posix_hits[:5]

    return dict(out), dict(samples)


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

def walk(root):
    for dirpath, _, files in os.walk(root):
        for fn in files:
            if fn.endswith((".c", ".h")):
                yield os.path.join(dirpath, fn)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default="bearssl",
                    help="Directory to scan (default: bearssl)")
    ap.add_argument("--json", help="Write full JSON report to this path")
    ap.add_argument("--top", type=int, default=15,
                    help="Show top-N offenders per category")
    args = ap.parse_args()

    if not os.path.isdir(args.root):
        print("error: not a directory: %s" % args.root, file=sys.stderr)
        sys.exit(2)

    results = []
    total = defaultdict(int)
    files_with_any = 0
    files_scanned = 0
    for path in sorted(walk(args.root)):
        files_scanned += 1
        counts, samples = scan_file(path)
        nonzero = {k: v for k, v in counts.items() if v > 0}
        if nonzero:
            files_with_any += 1
            for k, v in nonzero.items():
                total[k] += v
        results.append({
            "path": os.path.relpath(path, args.root),
            "counts": counts,
            "samples": samples,
        })

    # Aggregate report
    print("BearSSL CW8/C89 compatibility audit")
    print("====================================")
    print("Scanned: %d files (%d .c, %d .h)" % (
        files_scanned,
        sum(1 for r in results if r["path"].endswith(".c")),
        sum(1 for r in results if r["path"].endswith(".h")),
    ))
    print("Files with at least one hit: %d" % files_with_any)
    print()
    print("Aggregate counts by category")
    print("----------------------------")
    for k in sorted(total, key=lambda x: -total[x]):
        print("  %-22s %d" % (k, total[k]))
    print()

    # Top offenders per category
    print("Top offenders per category (top %d)" % args.top)
    print("-----------------------------------")
    categories = sorted(total.keys())
    for cat in categories:
        ranked = sorted(
            [r for r in results if r["counts"].get(cat, 0) > 0],
            key=lambda r: -r["counts"][cat],
        )[:args.top]
        if not ranked:
            continue
        print()
        print("  %s (total=%d, %d files)" % (
            cat, total[cat],
            sum(1 for r in results if r["counts"].get(cat, 0) > 0),
        ))
        for r in ranked:
            print("    %6d  %s" % (r["counts"][cat], r["path"]))

    if args.json:
        with open(args.json, "w") as f:
            json.dump({
                "files_scanned": files_scanned,
                "files_with_any": files_with_any,
                "aggregate": dict(total),
                "files": results,
            }, f, indent=2, sort_keys=True)
        print()
        print("Wrote full report: %s" % args.json)


if __name__ == "__main__":
    main()
