/*
 * This file is part of LibCSS
 * Licensed under the MIT License,
 *		  http://www.opensource.org/licenses/mit-license.php
 * Copyright 2026 MacSurf (fixes151)
 *
 * Cascade -macsurf-grid-col-span. Stores a packed int32 directly in
 * the inner _i struct (memcmp-safe scalar). Default 0 means "no
 * placement set"; layout treats this as auto-flow / span 1.
 *
 * fixes158 extends storage from uint8 col-span to a full packed int32
 * with four 8-bit fields: col_span (low), col_start, row_start,
 * row_span (high). See autogenerated_computed.h for the bit layout.
 */

#include <stdlib.h>
#include <string.h>

#include "bytecode/bytecode.h"
#include "bytecode/opcodes.h"
#include "select/propset.h"
#include "select/propget.h"
#include "utils/utils.h"

#include "select/properties/properties.h"
#include "select/properties/helpers.h"

css_error css__cascade_macsurf_grid_col_span(uint32_t opv,
		css_style *style, css_select_state *state)
{
	int32_t span = 0;
	bool is_set = false;

	if (hasFlagValue(opv) == false) {
		if (getValue(opv) == 0x0080) { /* SET */
			is_set = true;
			span = *((css_fixed *) style->bytecode);
			advance_bytecode(style, sizeof(css_fixed));
			/* fixes158: accept the full packed int32 verbatim.
			 * Negative values are treated as unset. No upper
			 * clamp - the placement bits in the high bytes are
			 * load-bearing now. */
			if (span < 0) span = 0;
		}
	}

	if (css__outranks_existing(getOpcode(opv), isImportant(opv), state,
			getFlagValue(opv))) {
		state->computed->i.macsurf_grid_col_span =
				is_set ? span : 0;
	}

	return CSS_OK;
}

css_error css__set_macsurf_grid_col_span_from_hint(const css_hint *hint,
		css_computed_style *style)
{
	(void)hint;
	style->i.macsurf_grid_col_span = 0;
	return CSS_OK;
}

css_error css__initial_macsurf_grid_col_span(css_select_state *state)
{
	state->computed->i.macsurf_grid_col_span = 0;
	return CSS_OK;
}

css_error css__copy_macsurf_grid_col_span(
		const css_computed_style *from,
		css_computed_style *to)
{
	if (from == to) return CSS_OK;
	to->i.macsurf_grid_col_span = from->i.macsurf_grid_col_span;
	return CSS_OK;
}

css_error css__compose_macsurf_grid_col_span(
		const css_computed_style *parent,
		const css_computed_style *child,
		css_computed_style *result)
{
	/* fixes158: grid placement is per-item, not inherited from
	 * parent. Child's value wins outright. (Previously the fixes151
	 * implementation fell back to parent when child was 0 - harmless
	 * when col-span was only ever set on grid items, but with full
	 * placement we MUST NOT inherit `grid-column: 2` from a flex/grid
	 * parent into all its children.) */
	(void)parent;
	result->i.macsurf_grid_col_span = child->i.macsurf_grid_col_span;
	return CSS_OK;
}

uint32_t destroy_macsurf_grid_col_span(void *bytecode)
{
	(void)bytecode;
	return 0;
}
