/*
 * This file is part of LibCSS.
 * Licensed under the MIT License.
 */

#ifndef css_select_properties_s_transition_helpers_h_
#define css_select_properties_s_transition_helpers_h_

#include <stdlib.h>
#include <string.h>
#include "select/autogenerated_computed.h"

enum css_transition_inherit_flags {
	CSS_TRANS_INHERIT_PROP   = (1 << 0),
	CSS_TRANS_INHERIT_DUR    = (1 << 1),
	CSS_TRANS_INHERIT_TIMING = (1 << 2),
	CSS_TRANS_INHERIT_DELAY  = (1 << 3)
};

static inline css_computed_transition_data *css__ensure_transition_data(css_computed_style *style)
{
	css_computed_transition_data *d;
	if (style->transition_data != NULL)
		return style->transition_data;

	d = (css_computed_transition_data *)calloc(1, sizeof(css_computed_transition_data));
	if (d == NULL) return NULL;

	/* Default initial values */
	d->prop_count = 1;
	d->props[0].kind = CSS_TRANS_PROP_ALL;
	d->props[0].prop_id = 0;
	d->props[0].custom_name = NULL;

	d->duration_count = 1;
	d->durations[0] = 0;

	d->timing_count = 1;
	d->timings[0].type = CSS_TIMING_EASE;
	d->timings[0].x1 = (int32_t)(0.25 * 65536.0);
	d->timings[0].y1 = (int32_t)(0.1 * 65536.0);
	d->timings[0].x2 = (int32_t)(0.25 * 65536.0);
	d->timings[0].y2 = (int32_t)(1.0 * 65536.0);
	d->timings[0].step_count = 0;
	d->timings[0].step_pos = 0;

	d->delay_count = 1;
	d->delays[0] = 0;

	style->transition_data = d;
	return d;
}

static inline void css__free_transition_data(css_computed_transition_data *d)
{
	int i;
	if (d == NULL) return;
	for (i = 0; i < d->prop_count; i++) {
		if (d->props[i].kind == CSS_TRANS_PROP_CUSTOM_IDENT && d->props[i].custom_name != NULL) {
			lwc_string_unref(d->props[i].custom_name);
			d->props[i].custom_name = NULL;
		}
	}
	free(d);
}

static inline css_computed_transition_data *css__clone_transition_data(const css_computed_transition_data *src)
{
	css_computed_transition_data *dst;
	int i;
	if (src == NULL) return NULL;

	dst = (css_computed_transition_data *)malloc(sizeof(css_computed_transition_data));
	if (dst == NULL) return NULL;

	memcpy(dst, src, sizeof(css_computed_transition_data));
	for (i = 0; i < dst->prop_count; i++) {
		if (dst->props[i].kind == CSS_TRANS_PROP_CUSTOM_IDENT && dst->props[i].custom_name != NULL) {
			lwc_string_ref(dst->props[i].custom_name);
		}
	}
	return dst;
}

static inline bool css__is_default_transition_data(const css_computed_transition_data *d)
{
	if (d == NULL) return true;
	if (d->prop_count == 1 && d->props[0].kind == CSS_TRANS_PROP_ALL &&
		d->duration_count == 1 && d->durations[0] == 0 &&
		d->timing_count == 1 && d->timings[0].type == CSS_TIMING_EASE &&
		d->delay_count == 1 && d->delays[0] == 0) {
		return true;
	}
	return false;
}

#endif
