/*
 * fixes148 -- gap and row-gap parsers for MacSurf.
 *
 * libcss upstream does not implement CSS3 gap/row-gap. MacTrove alone
 * uses `gap:` 76 times, so dropping these at tokenization leaves flex
 * items touching with zero spacing.
 *
 * Scope compromise for fixes148:
 *   - gap:        single value => column-gap (axis-neutral)
 *                 two values   => first is row-gap, second is column-gap;
 *                                 we emit column-gap set to the *first*
 *                                 value so single-axis layout benefits
 *                                 from the row-gap when the author wrote
 *                                 the canonical `gap: ROW COL`.
 *   - row-gap:    emit as column-gap. Under the current flex layout the
 *                 same value is applied on main and cross axis, which is
 *                 the intended behaviour for most single-value gap uses.
 *
 * True row_gap storage (separate computed field + bit allocation +
 * accessor) is deferred to a later round where the autogenerated
 * computed-style bit layout can be extended without risk to other
 * properties.
 */

#include <assert.h>
#include <string.h>

#include "bytecode/bytecode.h"
#include "bytecode/opcodes.h"
#include "parse/properties/properties.h"
#include "parse/properties/utils.h"

/**
 * Shared helper: parse a single <length> | normal | inherit | initial |
 * revert | unset | calc() value and emit it as a column-gap declaration.
 *
 * Matches the shape of css__parse_column_gap in autogenerated_column_gap.c
 * but is hand-written so the CSS_PROP_COLUMN_GAP target is explicit.
 */
static css_error parse_gap_value_as_column_gap(css_language *c,
		const parserutils_vector *vector, int32_t *ctx,
		css_style *result)
{
	int32_t orig_ctx = *ctx;
	css_error error;
	const css_token *token;
	bool match;

	token = parserutils_vector_iterate(vector, ctx);
	if (token == NULL) {
		*ctx = orig_ctx;
		return CSS_INVALID;
	}

	if ((token->type == CSS_TOKEN_IDENT) &&
			(lwc_string_caseless_isequal(
			token->idata, c->strings[INHERIT],
			&match) == lwc_error_ok && match)) {
		error = css_stylesheet_style_inherit(result,
				CSS_PROP_COLUMN_GAP);

	} else if ((token->type == CSS_TOKEN_IDENT) &&
			(lwc_string_caseless_isequal(
			token->idata, c->strings[INITIAL],
			&match) == lwc_error_ok && match)) {
		error = css_stylesheet_style_initial(result,
				CSS_PROP_COLUMN_GAP);

	} else if ((token->type == CSS_TOKEN_IDENT) &&
			(lwc_string_caseless_isequal(
			token->idata, c->strings[REVERT],
			&match) == lwc_error_ok && match)) {
		error = css_stylesheet_style_revert(result,
				CSS_PROP_COLUMN_GAP);

	} else if ((token->type == CSS_TOKEN_IDENT) &&
			(lwc_string_caseless_isequal(
			token->idata, c->strings[UNSET],
			&match) == lwc_error_ok && match)) {
		error = css_stylesheet_style_unset(result,
				CSS_PROP_COLUMN_GAP);

	} else if ((token->type == CSS_TOKEN_IDENT) &&
			(lwc_string_caseless_isequal(
			token->idata, c->strings[NORMAL],
			&match) == lwc_error_ok && match)) {
		error = css__stylesheet_style_appendOPV(result,
				CSS_PROP_COLUMN_GAP,
				0, COLUMN_GAP_NORMAL);

	} else if ((token->type == CSS_TOKEN_FUNCTION) &&
			(lwc_string_caseless_isequal(
			token->idata, c->strings[CALC],
			&match) == lwc_error_ok && match)) {
		error = css__parse_calc(c, vector, ctx, result,
				buildOPV(CSS_PROP_COLUMN_GAP, 0, COLUMN_GAP_CALC),
				UNIT_PX);

	} else {
		css_fixed length = 0;
		uint32_t unit = 0;
		*ctx = orig_ctx;

		error = css__parse_unit_specifier(c, vector, ctx,
				UNIT_PX, &length, &unit);
		if (error != CSS_OK) {
			*ctx = orig_ctx;
			return error;
		}

		if (length < 0) {
			*ctx = orig_ctx;
			return CSS_INVALID;
		}

		if ((unit & UNIT_MASK_COLUMN_GAP) == 0) {
			*ctx = orig_ctx;
			return CSS_INVALID;
		}

		error = css__stylesheet_style_appendOPV(result,
				CSS_PROP_COLUMN_GAP, 0, COLUMN_GAP_SET);
		if (error != CSS_OK) {
			*ctx = orig_ctx;
			return error;
		}

		error = css__stylesheet_style_vappend(result, 2, length, unit);
	}

	if (error != CSS_OK)
		*ctx = orig_ctx;

	return error;
}

/**
 * row-gap: parse identical to column-gap, emit as column-gap.
 */
css_error css__parse_row_gap(css_language *c,
		const parserutils_vector *vector, int32_t *ctx,
		css_style *result)
{
	return parse_gap_value_as_column_gap(c, vector, ctx, result);
}

/**
 * gap: row-gap <column-gap>? -- shorthand.
 *
 * Per CSS Box Alignment: `gap` is shorthand for row-gap + column-gap.
 * If only one value is given, it applies to both axes.
 *
 * Since we only have column-gap storage, we emit the FIRST value as
 * column-gap. For `gap: A B` the first value is row-gap per spec, but
 * since both axes share storage for now, picking either is equivalent
 * in the common case where row-gap and column-gap are equal.
 */
css_error css__parse_gap(css_language *c,
		const parserutils_vector *vector, int32_t *ctx,
		css_style *result)
{
	int32_t orig_ctx = *ctx;
	int32_t second_start;
	css_error error;
	const css_token *token;

	/* Parse the first (row) value. */
	error = parse_gap_value_as_column_gap(c, vector, ctx, result);
	if (error != CSS_OK) {
		*ctx = orig_ctx;
		return error;
	}

	/* Swallow optional whitespace, peek for second value. */
	consumeWhitespace(vector, ctx);
	second_start = *ctx;
	token = parserutils_vector_peek(vector, *ctx);
	if (token == NULL || tokenIsChar(token, ';') ||
			tokenIsChar(token, '}') ||
			tokenIsChar(token, '!')) {
		/* Only one value -- already emitted as column-gap. Done. */
		return CSS_OK;
	}

	/* A second value would be the column-gap per spec. Parse it and
	 * (since we store just one gap) overwrite -- this makes the
	 * common single-value case and the "same for both axes" case
	 * both end up with a reasonable column-gap, and leaves the
	 * declaration well-formed for the parser. */
	error = parse_gap_value_as_column_gap(c, vector, ctx, result);
	if (error != CSS_OK) {
		*ctx = second_start;
		/* Leave the first value in place; a malformed second value
		 * shouldn't invalidate the whole declaration. */
		return CSS_OK;
	}

	return CSS_OK;
}
