/*
 * This file is part of LibCSS
 * Licensed under the MIT License,
 *                http://www.opensource.org/licenses/mit-license.php
 *
 * Copyright 2015 Michael Drake <tlsa@netsurf-browser.org>
 */

#include <string.h>

#include "select/arena.h"
#include "select/arena_hash.h"
#include "select/computed.h"
#include "autogenerated_propget.h"
#include "autogenerated_propset.h"

#define TU_SIZE 3037
#define TS_SIZE 5101

struct css_computed_style *table_s[TS_SIZE];


static inline uint32_t css__arena_hash_style(struct css_computed_style *s)
{
	return css__arena_hash((const uint8_t *) &s->i, sizeof(s->i));
}


static inline bool arena__compare_computed_content_item(
		const struct css_computed_content_item *a,
		const struct css_computed_content_item *b)
{
	if (a == NULL && b == NULL) {
		return true;

	} else if (a == NULL || b == NULL) {
		return false;
	}

	if (a->type != b->type) {
		return false;
	}

	return memcmp(a, b, sizeof(struct css_computed_content_item)) == 0;
}


static inline bool arena__compare_css_computed_counter(
		const struct css_computed_counter *a,
		const struct css_computed_counter *b)
{
	bool match;

	if (a == NULL && b == NULL) {
		return true;

	} else if (a == NULL || b == NULL) {
		return false;
	}

	if (a->value == b->value &&
			lwc_string_isequal(a->name, b->name,
					&match) == lwc_error_ok &&
			match == true) {
		return true;
	}

	return false;
}

/* fixes118: compare two 8-int macsurf grid track arrays. */
static inline bool arena__compare_grid_tracks(
		const int32_t *a, const int32_t *b)
{
	if (a == NULL && b == NULL) return true;
	if (a == NULL || b == NULL) return false;
	return memcmp(a, b, 8 * sizeof(int32_t)) == 0;
}

/* fixes344b: compare two 2-element css_color gradient-stop arrays
 * (8 bytes each). */
static inline bool arena__compare_macsurf_gradient_full(
		const css_color *a, const css_color *b)
{
	if (a == NULL && b == NULL) return true;
	if (a == NULL || b == NULL) return false;
	return memcmp(a, b, 2 * sizeof(css_color)) == 0;
}

/* fixes345: compare two 4-int radial-gradient size+position arrays. */
static inline bool arena__compare_macsurf_gradient_radial(
		const int32_t *a, const int32_t *b)
{
	if (a == NULL && b == NULL) return true;
	if (a == NULL || b == NULL) return false;
	return memcmp(a, b, 4 * sizeof(int32_t)) == 0;
}

/* fixes1159b: compare the calc-expression side slots. Pointer identity:
 * within one sheet an expression interns to a single lwc_string, so
 * equal styles match; pointers that differ only miss a dedup (safe) and
 * never merge wrongly. */
static inline bool arena__compare_calc_slots(
		lwc_string * const *a,
		lwc_string * const *b)
{
	uint32_t i;

	for (i = 0; i < MACSURF_CALC_SLOT_COUNT; i++) {
		if (a[i] != b[i]) {
			return false;
		}
	}

	return true;
}

/* fixes365b: compare two 7-int diagonal/3-stop gradient arrays. */
static inline bool arena__compare_macsurf_gradient_stops(
		const int32_t *a, const int32_t *b)
{
	if (a == NULL && b == NULL) return true;
	if (a == NULL || b == NULL) return false;
	return memcmp(a, b, 7 * sizeof(int32_t)) == 0;
}

static inline bool arena__compare_string_list(
		lwc_string **a,
		lwc_string **b)
{
	if (a == NULL && b == NULL) {
		return true;

	} else if (a == NULL || b == NULL) {
		return false;
	}

	while (*a != NULL && *b != NULL) {
		bool match;

		if (lwc_string_isequal(*a, *b, &match) != lwc_error_ok ||
				match == false) {
			return false;
		}

		a++;
		b++;
	}

	if (*a != *b) {
		return false;
	}

	return true;
}


static inline bool css__arena_style_is_equal(
		struct css_computed_style *a,
		struct css_computed_style *b)
{
	if (memcmp(&a->i, &b->i, sizeof(struct css_computed_style_i)) != 0) {
		return false;
	}

	if (!arena__compare_string_list(
			a->font_family,
			b->font_family)) {
		return false;
	}

	if (!arena__compare_css_computed_counter(
			a->counter_increment,
			b->counter_increment)) {
		return false;
	}

	if (!arena__compare_css_computed_counter(
			a->counter_reset,
			b->counter_reset)) {
		return false;
	}

	if (!arena__compare_computed_content_item(
			a->content,
			b->content)) {
		return false;
	}

	if (!arena__compare_grid_tracks(
			a->macsurf_grid_tracks,
			b->macsurf_grid_tracks)) {
		return false;
	}

	if (!arena__compare_grid_tracks(
			a->macsurf_grid_row_tracks,
			b->macsurf_grid_row_tracks)) {
		return false;
	}

	/* fixes1159b - calc-expression side slots. */
	if (!arena__compare_calc_slots(
			a->macsurf_calc_expr,
			b->macsurf_calc_expr)) {
		return false;
	}

	if (!arena__compare_macsurf_gradient_full(
			a->macsurf_gradient_full,
			b->macsurf_gradient_full)) {
		return false;
	}

	if (!arena__compare_macsurf_gradient_radial(
			a->macsurf_gradient_radial,
			b->macsurf_gradient_radial)) {
		return false;
	}

	/* fixes365b - diagonal/3-stop gradient extension. */
	if (!arena__compare_macsurf_gradient_stops(
			a->macsurf_gradient_stops,
			b->macsurf_gradient_stops)) {
		return false;
	}

	/* fixes361b - second box-shadow scalar. */
	if (a->box_shadow_2 != b->box_shadow_2) {
		return false;
	}
	/* fixes362 - third box-shadow scalar. */
	if (a->box_shadow_3 != b->box_shadow_3) {
		return false;
	}

	if (!arena__compare_string_list(
			a->cursor,
			b->cursor)) {
		return false;
	}

	if (!arena__compare_string_list(
			a->quotes,
			b->quotes)) {
		return false;
	}

	return true;
}

/* Externally exported semantic comparator. Documented in computed.h.
 * Only the inherited foreground `color` is ignored for COLOR_DIFF.  The
 * paint-only comparator below deliberately remains broader (background,
 * borders and outline) for the existing single-box paint path. */
enum css_computed_style_diff
css_computed_style_diff(const struct css_computed_style *a,
		const struct css_computed_style *b)
{
	struct css_computed_style tmp = *b;
	css_color c;
	uint8_t type;

	if (css__arena_style_is_equal((struct css_computed_style *)a, &tmp))
		return CSS_COMPUTED_STYLE_NO_DIFF;

	type = get_color(a, &c);
	set_color(&tmp, type, c);
	if (css__arena_style_is_equal((struct css_computed_style *)a, &tmp))
		return CSS_COMPUTED_STYLE_COLOR_DIFF;

	return CSS_COMPUTED_STYLE_OTHER_DIFF;
}

/* Externally exported fast-path comparator. Documented in computed.h */
bool css_computed_style_is_paint_only_diff(
		const struct css_computed_style *a,
		const struct css_computed_style *b)
{
	struct css_computed_style tmp = *b;
	css_color c;
	uint8_t type;

	type = get_background_color(a, &c);
	set_background_color(&tmp, type, c);
	type = get_border_top_color(a, &c);
	set_border_top_color(&tmp, type, c);
	type = get_border_right_color(a, &c);
	set_border_right_color(&tmp, type, c);
	type = get_border_bottom_color(a, &c);
	set_border_bottom_color(&tmp, type, c);
	type = get_border_left_color(a, &c);
	set_border_left_color(&tmp, type, c);
	type = get_outline_color(a, &c);
	set_outline_color(&tmp, type, c);

	return css__arena_style_is_equal((struct css_computed_style *)a, &tmp);
}


/* Internally exported function, documented in src/select/arena.h */
css_error css__arena_intern_style(struct css_computed_style **style)
{
	struct css_computed_style *s = *style;
	uint32_t hash, index;

	/* Don't try to intern an already-interned computed style */
	if (s->count != 0) {
		return CSS_BADPARM;
	}

	/* Need to intern the style block */
	hash = css__arena_hash_style(s);
	index = hash % TS_SIZE;
	s->bin = index;

	if (table_s[index] == NULL) {
		/* Can just insert */
		table_s[index] = s;
		s->count = 1;
	} else {
		/* Check for existing */
		struct css_computed_style *l = table_s[index];
		struct css_computed_style *existing = NULL;

		do {
			if (css__arena_style_is_equal(l, s)) {
				existing = l;
				break;
			}
			l = l->next;
		} while (l != NULL);

		if (existing != NULL) {
			css_computed_style_destroy(s);
			existing->count++;
			*style = existing;
		} else {
			/* Add to list */
			s->next = table_s[index];
			table_s[index] = s;
			s->count = 1;
		}
	}

	return CSS_OK;
}


/* Internally exported function, documented in src/select/arena.h */
enum css_error css__arena_remove_style(struct css_computed_style *style)
{
	uint32_t index = style->bin;

	if (table_s[index] == NULL) {
		return CSS_BADPARM;

	} else {
		/* Check for existing */
		struct css_computed_style *l = table_s[index];
		struct css_computed_style *existing = NULL;
		struct css_computed_style *prev = NULL;

		/* fixes899 (MacSurf) - unlink by POINTER IDENTITY, not by value.
		 * The caller (css_computed_style_destroy) is removing the exact
		 * style it is about to free(), so that precise pointer must leave
		 * the table. The old css__arena_style_is_equal() value-match could
		 * unlink a DIFFERENT but equal entry and leave the freed `style`
		 * linked in table_s[bin] -> the next bin walk dereferences freed
		 * memory and calls through a garbage vtable (PC=0x2710). This is the
		 * reconvert re-cascade UAF: a second cascade populates the global,
		 * never-reset arena with near-duplicate entries (the memcmp over
		 * css_computed_style_i is not a byte-identical replay across passes),
		 * so value-match collisions are guaranteed. Identity-match makes the
		 * whole mis-classification class degrade to a harmless duplicate/leak
		 * instead of a heap-corrupting UAF -- the OS 9 safety net. */
		do {
			if (l == style) {
				existing = l;
				break;
			}
			prev = l;
			l = l->next;
		} while (l != NULL);

		if (existing != NULL) {
			if (prev != NULL) {
				prev->next = existing->next;
			} else {
				table_s[index] = existing->next;
			}
		} else {
			return CSS_BADPARM;
		}
	}

	return CSS_OK;
}
