/*
 * This file is part of LibCSS
 * Licensed under the MIT License,
 *                http://www.opensource.org/licenses/mit-license.php
 * Copyright 2009 John-Mark Bell <jmb@netsurf-browser.org>
 */

#ifndef css_select_propset_h_
#define css_select_propset_h_

/* Defensive empty define for CW8 — see notes in stylesheet.h. */
#ifndef _ALIGNED
#define _ALIGNED
#endif

#include <string.h>

#include <libcss/computed.h>
#include "computed.h"
#include "autogenerated_propset.h"

#endif
