#!/usr/bin/env python3
from pathlib import Path
p = Path('browser/netsurf/content/handlers/html/box_manipulate.c')
s = p.read_text()

old = '''{\n\tunsigned int i;\n\tstruct box *box;\n\n\tbox = talloc_zero(context, struct box);\n\tif (!box) {\n\t\treturn 0;\n\t}\n\n\ttalloc_set_destructor(box, box_talloc_destructor);\n\n\tbox->type = BOX_INLINE;\n\tbox->flags = 0;\n\tbox->flags = style_owned ? (box->flags | STYLE_OWNED) : box->flags;\n\tbox->styles = styles;\n\tbox->style = style;\n\tbox->x = box->y = 0;\n\tbox->width = UNKNOWN_WIDTH;\n\tbox->height = 0;\n\tbox->descendant_x0 = box->descendant_y0 = 0;\n\tbox->descendant_x1 = box->descendant_y1 = 0;\n\tfor (i = 0; i != 4; i++)\n\t\tbox->margin[i] = box->padding[i] = box->border[i].width = 0;\n\tbox->scroll_x = box->scroll_y = NULL;\n\tbox->min_width = 0;\n\tbox->max_width = UNKNOWN_MAX_WIDTH;\n\tbox->byte_offset = 0;\n\tbox->text = NULL;\n\tbox->length = 0;\n\tbox->space = 0;\n\tbox->href = (href == NULL) ? NULL : nsurl_ref(href);\n\tbox->target = target;\n\tbox->title = title;\n\tbox->columns = 1;\n\tbox->rows = 1;\n\tbox->start_column = 0;\n\tbox->next = NULL;\n\tbox->prev = NULL;\n\tbox->children = NULL;\n\tbox->last = NULL;\n\tbox->parent = NULL;\n\tbox->inline_end = NULL;\n\tbox->float_children = NULL;\n\tbox->float_container = NULL;\n\tbox->next_float = NULL;\n\tbox->cached_place_below_level = 0;\n\tbox->list_value = 1;\n\tbox->list_marker = NULL;\n\tbox->col = NULL;\n\tbox->gadget = NULL;\n\tbox->usemap = NULL;\n\tbox->id = id;\n\tbox->background = NULL;\n\tbox->object = NULL;\n\tbox->object_params = NULL;\n\tbox->iframe = NULL;\n\tbox->node = NULL;\n\n\treturn box;\n}\n'''
new = '''{\n\tstruct box *box;\n\n\t/* talloc_zero has already cleared every ordinary zero/NULL field.\n\t * Only initialise non-zero sentinels/defaults and caller-owned refs here. */\n\tbox = talloc_zero(context, struct box);\n\tif (!box) {\n\t\treturn 0;\n\t}\n\n\ttalloc_set_destructor(box, box_talloc_destructor);\n\n\tbox->type = BOX_INLINE;\n\tif (style_owned)\n\t\tbox->flags = STYLE_OWNED;\n\tbox->styles = styles;\n\tbox->style = style;\n\tbox->width = UNKNOWN_WIDTH;\n\tbox->max_width = UNKNOWN_MAX_WIDTH;\n\tbox->href = (href == NULL) ? NULL : nsurl_ref(href);\n\tbox->target = target;\n\tbox->title = title;\n\tbox->columns = 1;\n\tbox->rows = 1;\n\tbox->list_value = 1;\n\tbox->id = id;\n\n\treturn box;\n}\n'''
assert old in s, 'box_create initializer no longer matches expected source'
s = s.replace(old, new, 1)
p.write_text(s)
