#!/bin/bash
# Regenerates macos9_brotli.c / macos9_brotli.h — the single-file C89 Brotli
# decoder vendored into the MacSurf macos9 frontend — from the upstream
# google/brotli sources.
#
# Source: the TenFourFox mirror of google/brotli (the decoder is byte-identical
# to upstream's c/ tree; TenFourFox is kept because it is the PPC-era-proven
# snapshot this project can trust):
#     /home/patrick/Webs/tenfourfox/modules/brotli/
# Only the DECODER subset is vendored (dec/ + common/ + include/brotli).
#
# Why flatten: MacSurf builds with CodeWarrior 8, whose access-path include
# resolution is fragile ("CW8 cannot resolve relative includes from within
# headers found via access paths (simple names excepted)" — the gotchas doc).
# A single self-contained .c keeps every include a simple name from the
# frontends/macos9 root and adds exactly ONE file to MacSurf.mcp. This mirrors
# how lodepng.c already sits in this frontend.
#
# The output is C89 (CW8): the generator strips the internal #includes,
# patches the one C++-style comment upstream ships, and forces BROTLI_INLINE
# to empty under __MWERKS__ (CW8 has no `inline`). macos9_brotli.h is written
# next to it and contains the public surface only — macos9_woff2.c (the WOFF2
# reconstructor) calls BrotliDecoderDecompress() through it.
#
# Usage: tools/flatten_brotli.sh [path-to-brotli-tree]
# (defaults to the TenFourFox copy above)

set -e

SRC=${1:-/home/patrick/Webs/tenfourfox/modules/brotli}
OUTDIR="$(cd "$(dirname "$0")/.." && pwd)/browser/netsurf/frontends/macos9"
OUT_C="$OUTDIR/macos9_brotli.c"
OUT_H="$OUTDIR/macos9_brotli.h"

test -f "$SRC/dec/decode.c" || {
    echo "cannot find brotli decoder at $SRC" >&2
    exit 1
}

# Internal includes stripped from the flattened file (system includes kept).
STRIP='^[[:space:]]*#include[[:space:]]*[<"](brotli/|\.\./common/|\./|\.\./include/)'

emit_header() {
    cat >> "$OUT_C" <<'EOF'
/*
 * MacSurf - macos9_brotli.c
 *
 * Single-file C89 Brotli decompressor, GENERATED by tools/flatten_brotli.sh
 * from google/brotli (MIT license, sections below) via the TenFourFox mirror.
 * Do not edit by hand — regenerate and re-verify with the harness WOFF2 test
 * (Test 65). Only the decoder subset is vendored; macos9_woff2.c is the only
 * consumer (WOFF2 @font-face reconstruction).
 *
 * The sections below retain their upstream copyright headers.
 */
EOF
}

emit_pub_header() {
    cat > "$OUT_H" <<'EOF'
/*
 * MacSurf - macos9_brotli.h
 *
 * Public surface of the vendored single-file Brotli decoder (macos9_brotli.c,
 * generated by tools/flatten_brotli.sh from google/brotli, MIT). The full
 * decoder internals live in the .c; this header exposes only what the WOFF2
 * reconstructor (macos9_woff2.c) needs.
 */

#ifndef MACSURF_MACOS9_BROTLI_H
#define MACSURF_MACOS9_BROTLI_H

#include <stddef.h>
#include <stdint.h>

/* Result of a one-shot BrotliDecoderDecompress() call. The enum and the
 * prototype below are byte-identical to the ones inside macos9_brotli.c
 * (from include/brotli/decode.h) so the declarations never diverge. */
typedef enum {
  BROTLI_DECODER_RESULT_ERROR = 0,
  BROTLI_DECODER_RESULT_SUCCESS = 1,
  BROTLI_DECODER_RESULT_NEEDS_MORE_INPUT = 2,
  BROTLI_DECODER_RESULT_NEEDS_MORE_OUTPUT = 3
} BrotliDecoderResult;

/* One-shot memory-to-memory decompression (the WOFF2 path knows the exact
 * uncompressed size up front, so no streaming/growable machinery is needed).
 *
 *   encoded_size / encoded_buffer : the brotli stream
 *   *decoded_size                 : in  = capacity of decoded_buffer
 *                                   out = bytes written on SUCCESS
 *   decoded_buffer                : caller-owned output
 *
 * Returns BROTLI_DECODER_RESULT_SUCCESS (1) on success; ERROR (0) if the
 * stream is corrupt, the buffer is too small, or allocation failed.
 */
BrotliDecoderResult BrotliDecoderDecompress(
        size_t encoded_size, const uint8_t encoded_buffer[],
        size_t *decoded_size, uint8_t decoded_buffer[]);

#endif /* MACSURF_MACOS9_BROTLI_H */
EOF
}

# ---- generate the flattened .c --------------------------------------------
: > "$OUT_C"
emit_header

# system includes (once, at the top — the per-file ones are stripped)
{
    printf '#include <stdlib.h>\n#include <string.h>\n#include <stdint.h>\n'
} >> "$OUT_C"

cat >> "$OUT_C" <<'EOF'

#if defined(__cplusplus) || defined(c_plusplus)
extern "C" {
#endif

/* <<<< generated: internal headers (google/brotli) >>>>
EOF

# headers first, in dependency order
for h in \
    include/brotli/types.h \
    include/brotli/port.h \
    include/brotli/decode.h \
    common/version.h \
    common/platform.h \
    common/constants.h \
    common/context.h \
    common/dictionary.h \
    common/transform.h \
    dec/prefix.h \
    dec/bit_reader.h \
    dec/huffman.h \
    dec/state.h ; do
    printf '\n/* ========== %s ========== */\n' "$h" >> "$OUT_C"
    grep -v -E "$STRIP" "$SRC/$h" >> "$OUT_C"
done

# CW8 has no `inline`: force the inline macros empty after platform.h.
cat >> "$OUT_C" <<'EOF'

/* CW8 (__MWERKS__) has no `inline`: neutralize the upstream inline macros. */
#if defined(__MWERKS__)
#undef  BROTLI_MAYBE_INLINE
#undef  BROTLI_INLINE
#define BROTLI_MAYBE_INLINE
#define BROTLI_INLINE
#endif

/* <<<< generated: internal sources (google/brotli), dependency order >>>>
EOF

for f in \
    common/constants.c \
    common/context.c \
    common/dictionary.c \
    common/transform.c \
    common/platform.c \
    dec/bit_reader.c \
    dec/huffman.c \
    dec/state.c \
    dec/decode.c ; do
    printf '\n/* ========== %s ========== */\n' "$f" >> "$OUT_C"
    grep -v -E "$STRIP" "$SRC/$f" >> "$OUT_C"
done

# fix the ONE C++-style comment upstream ships (dictionary.c BrotliSetDictionaryData)
sed -i 's|BROTLI_UNUSED(data);  // Appease -Werror=unused-parameter|BROTLI_UNUSED(data);  /* appease -Werror=unused-parameter */|' "$OUT_C"

cat >> "$OUT_C" <<'EOF'

#if defined(__cplusplus) || defined(c_plusplus)
}
#endif
EOF

emit_pub_header

echo "wrote $OUT_C ($(wc -l < "$OUT_C") lines) and $OUT_H"
